name: "[1] Validação Feature"

on:
  push:
    branches:
      - feature-*
      - feature/*
  pull_request:
    branches:
      - feature-*
      - feature/*

permissions:
  deployments: write
  contents: write
  statuses: write
  actions: write
  checks: read
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  java-maven-build:
    name: Java-Maven Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitActions
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B -DskipTests=true package --file pom.xml

  java-maven-test:
    name: Java-Maven Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitActions
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Test with Maven
        run: mvn -B test --file pom.xml

  pr-feature-to-develop:
    name: PR feature to develop
#    needs:
#      - java-maven-build
#      - java-maven-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitActions
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: npm install

      - name: Open pull request
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: '[Example] Simple demo',
              owner,
              repo,
              head: '${{ github.ref_name }}',
              base: 'develop',
              body: [
                'This PR is auto-generated by',
                '[actions/github-script](https://github.com/actions/github-script).'
              ].join('\n')
            });
