name: "[3] Deploy - master"

on:
  pull_request:
    types:
      - closed
    branches:
      - master

permissions:
  contents: read

jobs:
  java-maven-build:
    name: Java-Maven Build
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    outputs:
      project_version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Checkout GitActions
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B -DskipTests=true package --file pom.xml

      - name: Obter versão do projeto
        id: get_version
        run: |
          echo "::set-output name=version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"

  deploy:
    name: Deploy AWS EB - PROD
    needs:
      - java-maven-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitActions
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B -DskipTests=true package --file pom.xml

      - name: Criar app.jar
        run: cp target/transporte-escolar-lista-presenca-*.jar target/app.jar

      - name: Obter TAG
        id: obter-tag
        run: echo "tag_version=$(git describe --tags $(git rev-list --tags --max-count=1))" >> "$GITHUB_ENV"

      - name: Imprimir número da execução atual
        run: echo "O número da execução atual é $GITHUB_RUN_ID"

      - name: Imprimir hash do commit
        run: echo "O hash do commit é $GITHUB_SHA"

      - name: Imprimir versão do projeto
        run: |
          echo "A versão do projeto é: ${{ needs.java-maven-build.outputs.project_version }}"

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: "api-telp-v1"
          environment_name: "api-telp-v1-prod"
          version_label: "${{ needs.java-maven-build.outputs.project_version }}"
          region: "sa-east-1"
          deployment_package: "./target/app.jar"
