name: "[1] Java CI with Maven"

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

permissions:
  deployments: write
  contents: write
  statuses: write
  actions: write
  checks: read
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  java-maven-build:
    name: Java-Maven Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitActions
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B -DskipTests=true package --file pom.xml

  java-maven-test:
    name: Java-Maven Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitActions
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Test with Maven
        run: mvn -B test --file pom.xml

  bump-version:
    name: Bump-Maven
    needs:
      - java-maven-build
      - java-maven-test
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.bump.outputs.version }}
    steps:
      - name: Checkout GitActions
        uses: actions/checkout@v3

      ### usar #major, #minor ou #patch no commit
      - name: Bump Version
        id: bump
        uses: nnichols/maven-version-bump-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Version
        run: "echo 'New Version: ${{steps.bump.outputs.version}}'"

  create-release:
    name: Create release
    needs:
      - bump-version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitActions
        uses: actions/checkout@v3

      - name: Create release branch
        run: |
          git checkout develop
          git checkout -b release
          git push -f origin release

  pr-release-to-master:
    name: PR release to master
    needs:
      - create-release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitActions
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "Automated PR from release to master. version: ${{ needs.bump-version.outputs.version }}"
          commit-message: "Automated commit message. version: ${{ needs.bump-version.outputs.version }}"
          body: "Please review and merge this pull request to deploy the release."
          branch: "release"
          base: "master"