name: "[2] Deploy"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  deployments: write
  contents: write
  statuses: write
  actions: write
  checks: read
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  java-maven-build:
    name: Java-Maven Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitActions
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B -DskipTests=true package --file pom.xml

  deploy:
    name: Deploy AWS EB
    needs:
      - java-maven-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitActions
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B -DskipTests=true package --file pom.xml

      - name: Criar app.jar
        run: cp target/transporte-escolar-lista-presenca-*.jar target/app.jar

      - name: Obter TAG
        id: obter-tag
        run: echo "tag_version=$(git describe --tags $(git rev-list --tags --max-count=1))" >> "$GITHUB_ENV"

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v19
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: "api-telp-v1"
          environment_name: "api-telp-v1-dev"
          version_label: "0.1.0-alpha"
          region: "sa-east-1"
          deployment_package: "./target/app.jar"
